### ISSUE TITLE
Server doesn't start (solved)

### ISSUE THREAD

**Issue by erwann-sh** [Zerschranzer/Ark-Survival-ascended-dedicated-server-without-docker#1]
deleted

**Comment by Zerschranzer** [comment]
> the instance start, but stop after a minute, and the server never show up. The base seems to be correctly installed. 

That usually happens when the server tries to load a map or mod that doesn't exist. Have you tried entering a different map or starting the server with the default config? (No mods, TheIsland_WP) Are all dependencies installed? Which distribution are you using? Send me the content of your config file located in the folder "instances/<instancename>/instance_config.ini" (remember to remove sensitive data like passwords) so I can test it.

**Comment by erwann-coffee** [comment]
The server is default config!  Are there other dependencies? Server is Debian 12. 

*instance_config.ini*
`[ServerSettings]
ServerName=ARKAscended.eu Test Server
ServerPassword=
ServerAdminPassword=adminpassword
MaxPlayers=70
MapName=TheIsland_WP
RCONPort=27020
QueryPort=27015
Port=7777
ModIDs=
SaveDir=theisland
ClusterID=`

Also this in *server.log*:
`wine: setpriority 3 for pid -1 failed: 3`

**Comment by Zerschranzer** [comment]
Try leaving the "SaveDir" value in the instance_config.ini at its default setting when creating a new instance. I just skimmed through the code and think I found a potential issue with handling the save directories. I'll take a closer look when I'm home. By the way, the wine error is normal on Debian. I still need to figure out why it occurs, but it usually doesn't prevent the server from starting. The required dependencies are just the ones checked when running the script. I tested it in Docker. Also, try avoiding spaces in the server name as a test, although that shouldn't be the issue either.

**Comment by erwann-coffee** [comment]
Alright let me know! It's the same without the SaveDir value, and now, I also get an error "tcp connection refused" with the RCON, I did not have that one few hours ago... I really don't understand.

**Comment by Zerschranzer** [comment]
Hello,

I just created a fresh Docker container with the latest Debian 12 image to reproduce your problem and check for missing packages. I proceeded as follows:

1. **Created a new user with sudo rights** and switched to the new user.
2. **Cloned the repository** and ran the `ark_instance_manager.sh` script.
3. **Installed dependencies**:
   ```
   sudo dpkg --add-architecture i386
   sudo apt update
   sudo apt-get install wget libc6:i386 libstdc++6:i386 libncursesw6:i386 python3 libfreetype6:i386 libfreetype6:amd64 procps
   ```
4. **Installed Base Server** via the script. `1) Install/Update Base Server`
5. **Created a new instance**:
   - In the menu option `3) Create New Instance`, created an instance named `This Is a Test`.
   - Adjusted the configuration as follows:
     ```
     [ServerSettings]
     ServerName=This Is a Test
     ServerPassword=
     ServerAdminPassword=adminpassword
     MaxPlayers=70
     MapName=TheIsland_WP
     RCONPort=27020
     QueryPort=27015
     Port=7777
     ModIDs=
     SaveDir=test
     ClusterID=
     ```
6. **Started the instance**:
   - Started the instance via `5) Start All Instances`.
   - The server has been running without issues for over 10 minutes.
   - RCON commands are also working; when entering `saveworld`, I receive the confirmation `World Saved`.
7. **Renamed the instance** to test for possible issues with save directories. No errors occurred here either, and the server continues to run stably.

**Conclusion:**
Based on these tests, I strongly suspect that the problem lies in your environment. Therefore, please check the following:

- **Dependencies**:
  - Did you run `sudo dpkg --add-architecture i386` and then install the required packages?
  - Check if there were any error messages during package installation.
- **User rights**:
  - Do **not** run the script as root.
  - Create a separate user with sudo rights and run the script under this user:
    ```
    sudo adduser arkserver
    sudo usermod -aG sudo arkserver
    su - arkserver
    ```
- **Running processes or services**:
  - Are there other programs or services that might be using ports **7777**, **27015**, or **27020**?
  - Check this with `net-tools`:
    ```
    sudo netstat -tulpn | grep -E '7777|27015|27020'
    ```
  - Ensure these ports are not blocked by other applications.
- **Firewall settings**:
  - If a firewall like ufw is active, open the required ports:
    ```
    sudo ufw allow 7777
    sudo ufw allow 27015
    sudo ufw allow 27020
    ```
- **Check logs**:
  - Examine the logs in `arkserverdir/server-files/ShooterGame/Saved/Logs/ShooterGame.log`
- **Server name and SaveDir**:
  - Although spaces in the `ServerName` and a custom `SaveDir` didn't cause problems for me, you could try setting the `ServerName` without spaces and enter the default value in `SaveDir` to see if it makes a difference.
- **RCON connection**:
  - The message `tcp connection refused` indicates that the RCON port is not reachable. This is normal if the server is not running :P
- **Wine error message**:
  - The message `wine: setpriority 3 for pid -1 failed: 3` is known and can be ignored. It should not affect the server start.

If the problem persists, it would be helpful if you could provide detailed logs, especially the `ShooterGame.log` and any error messages in `server.log`. This way, I can better understand where the problem lies and help you more specifically.

**Comment by erwann-coffee** [comment]
Hello, I have reinstalled everything several times, installed the dependencies, and followed the same process as you, but unfortunately the problem persists... I no longer have the RCON error, I can "access" it before having a timeout when the instance shuts down.

The instant remains active for about a minute after launch, the server does not appear in the list and I cannot connect with the IP either.


**Config**
```
[ServerSettings]
ServerName=arktest123
ServerPassword=
ServerAdminPassword=adminpassword
MaxPlayers=70
MapName=TheIsland_WP
RCONPort=27020
QueryPort=27015
Port=7777
ModIDs=
SaveDir=test
ClusterID=
```

**ShooterGame.log**
```
[2024.10.13-09.54.26:644][  0]Log file open, 10/13/24 09:54:26
[2024.10.13-09.54.26:644][  0]LogMemory: Platform Memory Stats for WindowsServer
[2024.10.13-09.54.26:644][  0]LogMemory: Process Physical Memory: 368.09 MB used, 410.01 MB peak
[2024.10.13-09.54.26:644][  0]LogMemory: Process Virtual Memory: 341.78 MB used, 341.78 MB peak
[2024.10.13-09.54.26:644][  0]LogMemory: Physical Memory: 625.31 MB used,  7138.00 MB free, 7763.31 MB total
[2024.10.13-09.54.26:644][  0]LogMemory: Virtual Memory: 625.32 MB used,  7138.00 MB free, 7763.32 MB total
[2024.10.13-09.54.27:606][  0]11

[2024.10.13-09.54.27:624][  0]ARK Version: 54.11
[2024.10.13-09.54.28:118][  0]LogCFCore: SetSettings called:
{
	"defaultLanguage": "en",
	"gameId": 83374,
	"apiKey": "*****1aZe",
	"maxConcurrentInstallations": 3,
	"modsDirectory": "ShooterGame/Mods",
	"modsDirectoryMode": "CFCore",
	"userDataDirectory": "ShooterGame/ModsUserData",
	"isServer": true,
	"isServerPcOnly": false,
	"throttling":
	{
		"diskWriteBytesPerSec": 0
	},
	"premiumMods":
	{
		"publicKeyPem": "*****"
	},
	"logger":
	{
		"enabled": true,
		"history": 8,
		"maxSizeInMB": 2
	},
	"dynamicContentCategoryIds": [ 6844 ]
}
[2024.10.13-09.54.28:118][  0]LogCFCore: InternalSettings called:
{
	"apiBaseUrl": "https://api.curseforge.com",
	"chunkedUploadServerUrl": "https://chunk-uploads.curseforge.com",
	"analyticsUrl": "https://analyticsnew.overwolf.com/analytics/Counter",
	"userAgent": "cfcore.ue 1.0.99",
	"platform": "windows",
	"pluginVersion": "1.0.99",
	"httpFileDownloadTimeoutSecs": 1200
}
[2024.10.13-09.54.28:120][  0]LogCFCore: Warning: Couldn't load mods library from disk
[2024.10.13-09.54.28:157][  0]LogCFCore: User context not loaded from disk
[2024.10.13-09.54.28:158][  1]UShooterEngine::LoadGameMods with 0 mods
[2024.10.13-09.54.28:158][  1]No Primal Game Data Override, using default PrimalGameDataAsset.
[2024.10.13-09.54.29:130][  1]Default PrimalGameDataAsset instance created. Class is PrimalGameDataARKNX_BP_C_2147482292.
[2024.10.13-09.54.29:130][  1]Initialize Primal Game Data Override.
[2024.10.13-09.54.29:133][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_1
[2024.10.13-09.54.29:133][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_2
[2024.10.13-09.54.29:133][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_3
[2024.10.13-09.54.29:133][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_4
[2024.10.13-09.54.29:133][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_5
[2024.10.13-09.54.29:133][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_6
[2024.10.13-09.54.29:133][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_7
[2024.10.13-09.54.29:137][  1]Primal Game Data Took 0.00 seconds
[2024.10.13-09.54.29:143][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_1
[2024.10.13-09.54.29:143][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_2
[2024.10.13-09.54.29:143][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_3
[2024.10.13-09.54.29:143][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_4
[2024.10.13-09.54.29:143][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_5
[2024.10.13-09.54.29:143][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_6
[2024.10.13-09.54.29:143][  1]Added Explorer Note Entry: DEARJANE_EXP_NOTE_7
[2024.10.13-09.54.29:823][  1]Server: "arktest123" has successfully started!
[2024.10.13-09.55.03:736][  1]Commandline:  TheIsland_WP?listen?SessionName=arktest123?MaxPlayers=70?ServerPassword=?ServerAdminPassword=adminpassword?QueryPort=27015?Port=27020
27015
7777?RCONEnabled=True?RCONPort=27020?AltSaveDirectoryName=test -NoBattlEye -crossplay -NoHangDetection -useallavailablecores -nosteamclient -game -server -log -mods=
[2024.10.13-09.55.03:736][  1]Full Startup: 37.95 seconds

```


**server.log**
```
fsync: up and running.
```
*The Wine error message disappeared...*

**Comment by Zerschranzer** [comment]
Hello,

I had a closer look at your logs, and I noticed something that might explain the issue. Your server appears to have only **8 GB of physical memory** available:

```
[2024.10.13-09.54.26:644][  0]LogMemory: Physical Memory: 625.31 MB used,  7138.00 MB free, 7763.31 MB total
```

ARK is quite a memory-intensive game, and for a stable server performance, it's usually recommended to have at least **16 GB of RAM**. With only 8 GB, it’s very likely that the server runs out of memory shortly after starting, causing it to shut down after about a minute, as you've described.

I’m confident this is the cause of your problem. In my setup, the server uses almost 15 GB of RAM (as you can see in the screenshot), and you currently have only half of that available. To resolve this, I recommend increasing the amount of RAM on your VPS to 16 GB or more. Alternatively, you could try setting up a swap file temporarily, but that’s not a long-term solution, as it’s significantly slower than physical RAM and may still lead to instability.

Let me know if you need help setting up swap or if you have any other questions. However, as mentioned, using swap could still result in performance issues or even crashes.

**Comment by erwann-coffee** [comment]
Hello, it was indeed the issue, I'm sorry! Unfortunately, the server show up in the "player servers" list, which makes it impossible for a community server...  Too bad I didn't know that... Too bad it didn't work on the Test VPS before I discover that after buying a dedicated for hundreds of euros for nothing... But this is unrelated! F* Nitrado, and f* this game!
Still thank you for your help! Your script is simple to use and very good! Bye.

**Comment by Zerschranzer** [comment]
Note: The original user deleted all their comments, so here is a brief summary of the issue:

The user had a problem with their ARK: Survival Ascended server on a Debian 12 server, where it would crash after about one minute. I was unable to reproduce the issue in my own Debian 12 Docker environment. After a detailed analysis of the logs, it turned out that the user's server only had 8 GB of RAM, while the ARK server requires at least 16 GB. Once the user upgraded their RAM, the problem was resolved.

Based on this, the README has been updated to clarify that at least 16 GB of RAM is required to run the server stably.

**Comment by Zerschranzer** [comment]
Problem solved.

**Comment by Zerschranzer** [comment]
Problem solved.
